# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Academic theme
# https://jekyll-themes.com/academic/

title: spencer wilson
# title_html: <h1>spencer wilson</h1>
# pitch: optimizing for interesting
# cc:
description: optimizing for interesting

email: spencer@spewil.com

repo: https://github.com/spewil/website

curriculum:
  name: Resume
  url: /resume.pdf
author_display: true
author_website: "http://www.spewil.com"
twitter_username: its_me_spencer
github_username:  spewil
linkedin_username: spewil

nb_posts_page: 3

nav_links:
  - name: pictures ðŸ“¸
    url: /pictures/
    type: external
  - name: writing ðŸ–‹ï¸
    url: /posts/
  - name: reading ðŸ“š
    url: https://www.goodreads.com/review/list/66687559-spencer?shelf=currently-reading
    type: external
  - name: about me ðŸ¤“
    url: /about/

# description: >- # this means to ignore newlines until "baseurl:"
#   optimizing for interesting.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.spewil.com" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
# https://github.com/benbalter/jekyll-remote-theme
remote_theme: gaalcaras/academic
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# https://github.com/mmistakes/minimal-mistakes/issues/1992
# can't have github here for some reason...

google_analytics: true

kramdown:
  parse_block_html: true

excerpt_separator: <!--below excerpt-->

# source              : .
# destination         : ./_site
# collections_dir     : .
# plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
# layouts_dir         : _layouts
# data_dir            : _data
# includes_dir        : _includes
# sass:
#   sass_dir: _sass

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 5
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : []

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false


# # Exclude from processing.
# # The following items will not be processed, by default.
# # Any item listed under the `exclude:` key here will be automatically added to
# # the internal "default list".
# #
# # Excluded items can be processed by explicitly listing the directories or
# # their entries' file path in the `include:` list.
# #
# # exclude:
# #   - .sass-cache/
# #   - .jekyll-cache/
# #   - gemfiles/
# #   - Gemfile
# #   - Gemfile.lock
# #   - node_modules/
# #   - vendor/bundle/
# #   - vendor/cache/
# #   - vendor/gems/
# #   - vendor/ruby/
